### ISSUE TITLE
add docker get version  method

### ISSUE THREAD

**Issue by jiaosir-cn** [websoft9dev/role_docker#16]
adminer version: * @version 4.8.0

**Comment by jiaosir-cn** [comment]
adminmongo version: \"version\": \"0.0.23

**Comment by jiaosir-cn** [comment]
phpmyadmin version: \"version\": \"5.1.0\"

**Comment by zengxc-1996** [comment]
add  mongoexpress  version
add codiad  version
add rocketmqconsole version
add pgadmin version
add onlyofficedocumentserver version
add cmak version

**Comment by jiaosir-cn** [comment]
codeserver version: 3.9.0                      fc6d123da59a4e5a675ac8e080f66e032ba01a1b

**Comment by jiaosir-cn** [comment]
phppgadmin version: Version 5.6

**Comment by zengxc-1996** [comment]
"mongoexpress version: 0.54.0\""

**Comment by zengxc-1996** [comment]
"codiad version: 97f1331a"

**Comment by zengxc-1996** [comment]
"onlyofficedocumentserver version: 6.2.0-123"

**Comment by zengxc-1996** [comment]
"rocketmqconsole version: 2.0.0",
 "cmak version: 3.0.0.5",
  "pgadmin version: \"Version 5.0\" accesskey"

**Comment by zengxc-1996** [comment]
"portainer version: 2.1.1"

**Comment by qiaofeng1227** [comment]
Done
